apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  # annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /

spec:
        #defaultBackend:
        #resource:
        # apiGroup: k8s.example.com
        # kind: StorageBucket
        #name: static-assets
  rules:
  - host: localhost  #ec2-54-180-179-124.ap-northeast-2.compute.amazonaws.com
  - http:
      paths:
        - path: /audio
          pathType: Prefix 
          backend:
            service:
              name: choleor-audio-server
              port:
                number: 8001
        - path: /choreo
          pathType: Prefix
          backend:
            service:
              name: choleor-choreo-server
              port:
                number: 8002
        - path: /product
          pathType: Prefix
          backend:
            service:
              name: choleor-product-server
              port:
                number: 8003

# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.41.2/deploy/static/provider/cloud/deploy.yaml

# kubectl create secret generic regcred \
# --from-file=.dockerconfigjson=/home/jihee/.docker/config.json \
# --type=kubernetes.io/dockerconfigjson
