apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: choleor-choreo-db
  name: choreo-db-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
