apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: choleor-selection-cache
  name: choleor-selection-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: choleor-selection-cache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.network/choleor-audio-net: "true"
        io.kompose.service: choleor-selection-cache
    spec:
      containers:
        - args:
            - redis-server
            - '--requirepass dkredisaudio'
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: SELECTION_REDIS_PASSWORD
                  name: redis-env
          image: redis:6.0.9-alpine
          # livenessProbe:
          #   exec:
          #     command:
          #       - redis-cli -h 127.0.0.1:6380 ping
          #   failureThreshold: 5
          #   periodSeconds: 3
          #   timeoutSeconds: 1
          name: choleor-audio-selection-redis
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - mountPath: /data/
              name: audio-cache-selection-vol
      restartPolicy: Always
      volumes:
        - name: audio-cache-selection-vol
          persistentVolumeClaim:
            claimName: audio-cache-selection-vol
